-- catalog_returns: refunded vs returning can differ (third-party gift scenarios).

SELECT
    CAST('catalog' AS VARCHAR(10))           AS channel,
    CAST(cr_order_number AS BIGINT)          AS return_order_id,
    cr_item_sk                               AS item_sk,
    cr_refunded_customer_sk                  AS refunded_customer_sk,
    cr_returning_customer_sk                 AS returning_customer_sk,
    cr_refunded_cdemo_sk                     AS refunded_cdemo_sk,
    cr_refunded_hdemo_sk                     AS refunded_hdemo_sk,
    cr_refunded_addr_sk                      AS refunded_addr_sk,
    CAST(NULL AS INTEGER)                    AS store_sk,
    cr_call_center_sk                        AS call_center_sk,
    cr_catalog_page_sk                       AS catalog_page_sk,
    cr_warehouse_sk                          AS warehouse_sk,
    CAST(NULL AS INTEGER)                    AS web_page_sk,
    cr_ship_mode_sk                          AS ship_mode_sk,
    cr_reason_sk                             AS reason_sk,
    cr_returned_date_sk                      AS returned_date_sk,
    cr_returned_time_sk                      AS returned_time_sk,
    cr_return_quantity                       AS return_quantity,
    cr_return_amount                         AS return_amt,
    cr_return_tax                            AS return_tax,
    cr_return_amt_inc_tax                    AS return_amt_inc_tax,
    cr_fee                                   AS fee,
    cr_return_ship_cost                      AS return_ship_cost,
    cr_refunded_cash                         AS refunded_cash,
    cr_reversed_charge                       AS reversed_charge,
    cr_store_credit                          AS credit,
    cr_net_loss                              AS net_loss,
    _batch_id,
    _ingested_at,
    _source_file
FROM {{ source('bronze', 'catalog_returns') }}
