-- catalog_sales uses bill_customer_sk as the customer of record (payer).
-- Column order must match stg_store_sales / stg_web_sales.

SELECT
    CAST('catalog' AS VARCHAR(10))           AS channel,
    CAST(cs_order_number AS BIGINT)          AS sale_order_id,
    cs_item_sk                               AS item_sk,
    cs_bill_customer_sk                      AS customer_sk,
    cs_bill_cdemo_sk                         AS cdemo_sk,
    cs_bill_hdemo_sk                         AS hdemo_sk,
    cs_bill_addr_sk                          AS addr_sk,
    CAST(NULL AS INTEGER)                    AS store_sk,
    cs_call_center_sk                        AS call_center_sk,
    cs_catalog_page_sk                       AS catalog_page_sk,
    cs_warehouse_sk                          AS warehouse_sk,
    CAST(NULL AS INTEGER)                    AS web_page_sk,
    CAST(NULL AS INTEGER)                    AS web_site_sk,
    cs_ship_mode_sk                          AS ship_mode_sk,
    cs_promo_sk                              AS promo_sk,
    cs_sold_date_sk                          AS sold_date_sk,
    cs_ship_date_sk                          AS ship_date_sk,
    cs_sold_time_sk                          AS sold_time_sk,
    cs_quantity                              AS quantity,
    cs_wholesale_cost                        AS wholesale_cost,
    cs_list_price                            AS list_price,
    cs_sales_price                           AS sales_price,
    cs_ext_discount_amt                      AS ext_discount_amt,
    cs_ext_sales_price                       AS ext_sales_price,
    cs_ext_wholesale_cost                    AS ext_wholesale_cost,
    cs_ext_list_price                        AS ext_list_price,
    cs_ext_tax                               AS ext_tax,
    cs_coupon_amt                            AS coupon_amt,
    cs_ext_ship_cost                         AS ext_ship_cost,
    cs_net_paid                              AS net_paid,
    cs_net_paid_inc_tax                      AS net_paid_inc_tax,
    cs_net_paid_inc_ship                     AS net_paid_inc_ship,
    cs_net_paid_inc_ship_tax                 AS net_paid_inc_ship_tax,
    cs_net_profit                            AS net_profit,
    _batch_id,
    _ingested_at,
    _source_file
FROM {{ source('bronze', 'catalog_sales') }}
