-- web_sales uses bill_customer_sk as the customer of record.
-- Column order must match stg_store_sales / stg_catalog_sales.

SELECT
    CAST('web' AS VARCHAR(10))               AS channel,
    CAST(ws_order_number AS BIGINT)          AS sale_order_id,
    ws_item_sk                               AS item_sk,
    ws_bill_customer_sk                      AS customer_sk,
    ws_bill_cdemo_sk                         AS cdemo_sk,
    ws_bill_hdemo_sk                         AS hdemo_sk,
    ws_bill_addr_sk                          AS addr_sk,
    CAST(NULL AS INTEGER)                    AS store_sk,
    CAST(NULL AS INTEGER)                    AS call_center_sk,
    CAST(NULL AS INTEGER)                    AS catalog_page_sk,
    ws_warehouse_sk                          AS warehouse_sk,
    ws_web_page_sk                           AS web_page_sk,
    ws_web_site_sk                           AS web_site_sk,
    ws_ship_mode_sk                          AS ship_mode_sk,
    ws_promo_sk                              AS promo_sk,
    ws_sold_date_sk                          AS sold_date_sk,
    ws_ship_date_sk                          AS ship_date_sk,
    ws_sold_time_sk                          AS sold_time_sk,
    ws_quantity                              AS quantity,
    ws_wholesale_cost                        AS wholesale_cost,
    ws_list_price                            AS list_price,
    ws_sales_price                           AS sales_price,
    ws_ext_discount_amt                      AS ext_discount_amt,
    ws_ext_sales_price                       AS ext_sales_price,
    ws_ext_wholesale_cost                    AS ext_wholesale_cost,
    ws_ext_list_price                        AS ext_list_price,
    ws_ext_tax                               AS ext_tax,
    ws_coupon_amt                            AS coupon_amt,
    ws_ext_ship_cost                         AS ext_ship_cost,
    ws_net_paid                              AS net_paid,
    ws_net_paid_inc_tax                      AS net_paid_inc_tax,
    ws_net_paid_inc_ship                     AS net_paid_inc_ship,
    ws_net_paid_inc_ship_tax                 AS net_paid_inc_ship_tax,
    ws_net_profit                            AS net_profit,
    _batch_id,
    _ingested_at,
    _source_file
FROM {{ source('bronze', 'web_sales') }}
